### PR TITLE
adding privacy banner and updated privacy policy

### PR DESCRIPTION
**Pull request by gcolliso**

### CODE REVIEW

**Comment by gcolliso** [comment]
@derekcollison adding new privacy policy and cookie banner per Jan. 
Preview here https://synadia-website-5tkp8k7hg-connecteverything.vercel.app/

**Comment by derekcollison** [comment]
Possible to make it a bit more muted color wise instead of stark white?

Otherwise LGTM.

**Comment by gcolliso** [comment]
Sure - I was trying to match the website but I've updated them to shades of grey. 
https://synadia-website-kbybbk500-connecteverything.vercel.app/

**Review by derekcollison — APPROVED** [review]
LGTM

**Pull request merged**
